### ISSUE TITLE
Add while value to use controller with SK6812 RGBW

### ISSUE THREAD

**Issue by andrewostroumov** [samhstein/sp108e_ws2815#1]
Hello there, I've found your perfect component here and It really works for me but unfortunately it doesn't have while value support. So could you please add this? If only I can python I make a PR but my scope is golang / ruby

**Comment by andrewostroumov** [comment]
According to this repo white brightness is controlled by 0x08 (byte 5)
https://github.com/Lehkeda/SP108E_controller#change-white-led-brightness

**Comment by samhstein** [comment]
hi,

looks like you got to it before i had a chance, welcome to the python world!!! i don't have 
strips that support white so can't test but your code looks good / is merged.

thanks, sam

**Comment by andrewostroumov** [comment]
Thanks Sam, let's hope someone in HASS world will use it

**Comment by Harro65** [comment]
Is this still available after the changes config UI? 

Stability of this is great, however cant seem to control the white channel on the SK6812 RGBW leds. Any ideas how I can include in the integration?
