### ISSUE TITLE
No 'version' key in the manifest file for custom integration 'sp108e_ws2815'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'sp108e_ws2815'

### ISSUE THREAD

**Issue by kusok18** [samhstein/sp108e_ws2815#11]
No 'version' key in the manifest file for custom integration 'sp108e_ws2815'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'sp108e_ws2815'

**Comment by samhstein** [comment]
try the config-flow branch
