### ISSUE TITLE
Not working after upgrade core-2021.6.5

### ISSUE THREAD

**Issue by claudioluizs** [samhstein/sp108e_ws2815#12]
Hi, after upgrade from core 6.5 it's not working. Thank you so much.

**Comment by samhstein** [comment]
yea, hope to get to it over the weekend....

**Comment by samhstein** [comment]
seems to be back in action with 6.6

**Comment by claudioluizs** [comment]
Hello,
I'm  in  core-2021.7.0, and  it's not working yet. 
The message is "Platform error light.sp108e_ws2815 - Integration 'sp108e_ws2815' not found."
Thank you.

**Comment by samhstein** [comment]
hi,

switch to the cover-flow branch, im going to merge them together
soon...

thanks, sam
