### ISSUE TITLE
Nothing showing up in UI after custom_component added?

### ISSUE THREAD

**Issue by KenwoodFox** [samhstein/sp108e_ws2815#13]
Hello!

Im on the config-flow branch, and ive added the config to the custom_components directory. But i dont see anything new in the integrations pannel in the gui, any ideas on what to try next? Thanks so much!

**Comment by samhstein** [comment]
if your using the config-flow branch, the configuration.yaml is not used, should not be there...

**Comment by KenwoodFox** [comment]
> if your using the config-flow branch, the configuration.yaml is not used, should not be there...

what yaml?.. do i need to put something in the yaml? im on `config-flow` i thought that that branch dident use configuration.yaml?

now im confused, im expecting that using config-flow, i do *not* use the configuration.yaml, and use the gui instead, is that incorrect?

**Comment by samhstein** [comment]
sorry i confused things, with the config flow branch there is no yaml file.

it is working for me, did u just clone the single branch into the custom_components directory?

**Comment by Snille** [comment]
I'm having the same issue.... Downloaded the config-flow branch, unzipped and copied to custom_components:
![image](https://user-images.githubusercontent.com/1011699/127502041-a5471399-e406-475e-9ef5-e36f1ecf69dc.png)
I did rename the "sp108e_ws2815-config-flow" to "sp108e_ws2815" and restarted HA, was that correct? 
Where should I find the "configuration"?
Maybe make it a "HACS" repo, so it can be installed from in hacks. :)

**Comment by Snille** [comment]
Got it working, I missed that I needed to "add" it as "integration" in the integration page.... :)
![image](https://user-images.githubusercontent.com/1011699/127653314-9ed1f0a9-c8d1-4ad0-9916-5fafe367eab8.png)
However I'm on a 8806-strip, so the colors (wrong order) and some functions does not work correctly... Can I change this somewhere?

**Comment by KenwoodFox** [comment]
Ill try this asap!

**Comment by KenwoodFox** [comment]
Still getting the same issue :/
![image](https://user-images.githubusercontent.com/31870999/128052127-4ee5d235-a1c7-45d3-b725-8904bab5c5d1.png)

![image](https://user-images.githubusercontent.com/31870999/128052550-714ac5d6-4d9e-4980-ac28-e901715ce5a2.png)

**Comment by KenwoodFox** [comment]
I think i was able to get it working in the end, turns out it takes a bit and the component provides no entities 
![image](https://user-images.githubusercontent.com/31870999/128055378-78ae27f7-389c-4d81-bf15-ae53cdc4343a.png)

it seems to have installed and I gave it the IP I see in the app, but I don't see any activity..

**Comment by Snille** [comment]
@KenwoodFox after you have added the integration and given it a name you should see it like this (one for each unit added)...
(I have two)
![image](https://user-images.githubusercontent.com/1011699/128056573-83e428e2-6025-485b-b9d8-03e8f86a22ab.png)
Each unit have one device and one entity.
![image](https://user-images.githubusercontent.com/1011699/128056819-52a1f79a-8aa3-4218-bc8d-cf4b600c92c7.png)
Then you need to add a "light" in the GUI (Home screen or whatever you use).
![image](https://user-images.githubusercontent.com/1011699/128057042-87dd04f7-c454-4a13-9291-dd68e413c147.png)
There you can control stuff from the "dots" when the leds are on... :)
![image](https://user-images.githubusercontent.com/1011699/128057195-d8f7f813-7227-4b73-aacf-1fa4b10a946e.png)
I have managed to change effects and set brightness here. But not the color... However, that can be done from NodeRed. At least for me. :)

**Comment by KenwoodFox** [comment]
Thanks so much! I got it working after that and yeah I noticed the color is not stable here, wdym via node red though? Can I also set color via an automation?

**Comment by Snille** [comment]
NodeRed is a plugin for HA. I'm doing almost everything in there, instead of Automations.
![image](https://user-images.githubusercontent.com/1011699/128091667-f75e5fdb-ee8d-45d4-85dc-00fcadae8a8a.png)
I just think it's "easier" that way. But it all depends on what you like.
Have a look [here](https://www.youtube.com/watch?v=hBEb_FCLRU8) for more information... :)

**Comment by KenwoodFox** [comment]
I know~ I just meant how can you control the color via node red if hass cant control the color?

**Comment by KenwoodFox** [comment]
I also use node red for some tasks :3

**Comment by samhstein** [comment]
sorry for the delayed response, will be away from my development env for about a month or so...please feel free to hack away, and create pull requests. 

i did notice the color switching was messed up after upgrading my pi, hass. 

thanks, sam

**Comment by KenwoodFox** [comment]
> sorry for the delayed response, will be away from my development env for about a month or so...please feel free to hack away, and create pull requests.
> 
> i did notice the color switching was messed up after upgrading my pi, hass.
> 
> thanks, sam

Will do! Thanks for all the work you've done here,
