### ISSUE TITLE
Color not updating

### ISSUE THREAD

**Issue by cskiwi** [samhstein/sp108e_ws2815#14]
hi,

I have a WS2811 + sp108e

I just configured the integration (via branch `config-flow`) into home assistant and everything connected great.
However when I try to set a color it doesn't do anything, sometimes the picker just returns to original color.

Working from the `LED Shop` app it sets the color correctly + it updates in home assistant. 
Adjusting the brightness and effects works.

Am I doing something wrong? or am I missing something?
All help greatly appreciated!!

**Comment by VernonG07** [comment]
@cskiwi I've made a quick hack to get the color changing working on my fork for config-flow.  Will update with a better implementation when I actually debug to find out what's going onhttps://github.com/VernonG07/sp108e_ws2815/tree/config-flow

**Comment by samhstein** [comment]
sorry for the delay, was away for a couple months without access to try / test anything....
moved the color above the white value as they were now both getting passed...
