### ISSUE TITLE
Stopped working after HA (hassIO) update...

### ISSUE THREAD

**Issue by Snille** [samhstein/sp108e_ws2815#18]
Hi, I've been using your "flow" version of this for some time now.
But since a couple of HA updates back it's not working anymore.
I'm running:
Core Version core-2022.2.8
Supervisor Version supervisor-2022.01.1

Does anyone else have an issue?
Both my "led-controllers" are unavailable in HA.

**Comment by mich909** [comment]
Hi, i also have similar issue, but i know that my LED controller has changed IP address. In logs I have:
   "File "/config/custom_components/sp108e_ws2815/pyledshop/WifiLedShopLight.py", line 194, in send_command
    self._sock.connect((self._ip, self._port))
OSError: [Errno 113] Host is unreachable"
I updated ip address in congiguration.yaml, restarted server but still the same problem.
What do you have in your logs?

**Comment by Snille** [comment]
Mine is working again as well. :)
