### ISSUE TITLE
Unable to prepare setup for platform sp108e_ws2815.light

### ISSUE THREAD

**Issue by vicfalls** [samhstein/sp108e_ws2815#20]
Hi @samhstein 

since the last updates of HASS I have problems connecting to my SP108. 

Thanks for your support
Vic

Home Assistant 2022.9.1
Supervisor 2022.08.6
Operating System 8.5
Frontend 20220907.0 - latest

Logger: homeassistant.setup
Source: setup.py:320 
First occurred: 21:45:47 (1 occurrences) 
Last logged: 21:45:47

Unable to prepare setup for platform sp108e_ws2815.light: Platform not found (cannot import name 'ATTR_WHITE_VALUE' from 'homeassistant.components.light' (/usr/src/homeassistant/homeassistant/components/light/__init__.py)).

**Comment by wkelton** [comment]
Experiencing the same issue.

**Comment by wkelton** [comment]
`white_value` was removed:  https://github.com/home-assistant/core/pull/76926

Blog post:  https://developers.home-assistant.io/blog/2022/08/18/light_white_value_removed/

I'm not sure if this fully fixes this (due to the change of the deprecation), but I tried with this diff and was able to get it working for my use case:
```
diff --git a/pyledshop/WifiLedShopLight.py b/pyledshop/WifiLedShopLight.py
index 2710306..8abf50c 100644
--- a/pyledshop/WifiLedShopLight.py
+++ b/pyledshop/WifiLedShopLight.py
@@ -8,14 +8,13 @@ from homeassistant.components.light import (
     ATTR_COLOR_TEMP,
     ATTR_EFFECT,
     ATTR_HS_COLOR,
-    ATTR_WHITE_VALUE,
+    ATTR_WHITE,
     EFFECT_COLORLOOP,
     EFFECT_RANDOM,
     PLATFORM_SCHEMA,
     SUPPORT_BRIGHTNESS,
     SUPPORT_COLOR,
     SUPPORT_EFFECT,
-    SUPPORT_WHITE_VALUE,
     LightEntity,
 )
 import homeassistant.util.color as color_util
@@ -131,8 +130,8 @@ class WifiLedShopLight(LightEntity):
         self.set_color(r, g, b)
         return

-    if ATTR_WHITE_VALUE in kwargs:
-        self.set_white(kwargs[ATTR_WHITE_VALUE])
+    if ATTR_WHITE in kwargs:
+        self.set_white(kwargs[ATTR_WHITE])
         return

     if ATTR_EFFECT in kwargs:
@@ -268,4 +267,4 @@ class WifiLedShopLight(LightEntity):

   @property
   def supported_features(self):
-    return (SUPPORT_COLOR | SUPPORT_BRIGHTNESS | SUPPORT_WHITE_VALUE | SUPPORT_EFFECT)
+    return (SUPPORT_COLOR | SUPPORT_BRIGHTNESS | SUPPORT_EFFECT)
```

**Comment by Snille** [comment]
@wkelton Thank you, worked for me! :)

**Comment by fraanz97** [comment]
> `white_value` was removed: [home-assistant/core#76926](https://github.com/home-assistant/core/pull/76926)
> 
> Blog post: https://developers.home-assistant.io/blog/2022/08/18/light_white_value_removed/
> 
> I'm not sure if this fully fixes this (due to the change of the deprecation), but I tried with this diff and was able to get it working for my use case:
> 
> ```
> diff --git a/pyledshop/WifiLedShopLight.py b/pyledshop/WifiLedShopLight.py
> index 2710306..8abf50c 100644
> --- a/pyledshop/WifiLedShopLight.py
> +++ b/pyledshop/WifiLedShopLight.py
> @@ -8,14 +8,13 @@ from homeassistant.components.light import (
>      ATTR_COLOR_TEMP,
>      ATTR_EFFECT,
>      ATTR_HS_COLOR,
> -    ATTR_WHITE_VALUE,
> +    ATTR_WHITE,
>      EFFECT_COLORLOOP,
>      EFFECT_RANDOM,
>      PLATFORM_SCHEMA,
>      SUPPORT_BRIGHTNESS,
>      SUPPORT_COLOR,
>      SUPPORT_EFFECT,
> -    SUPPORT_WHITE_VALUE,
>      LightEntity,
>  )
>  import homeassistant.util.color as color_util
> @@ -131,8 +130,8 @@ class WifiLedShopLight(LightEntity):
>          self.set_color(r, g, b)
>          return
> 
> -    if ATTR_WHITE_VALUE in kwargs:
> -        self.set_white(kwargs[ATTR_WHITE_VALUE])
> +    if ATTR_WHITE in kwargs:
> +        self.set_white(kwargs[ATTR_WHITE])
>          return
> 
>      if ATTR_EFFECT in kwargs:
> @@ -268,4 +267,4 @@ class WifiLedShopLight(LightEntity):
> 
>    @property
>    def supported_features(self):
> -    return (SUPPORT_COLOR | SUPPORT_BRIGHTNESS | SUPPORT_WHITE_VALUE | SUPPORT_EFFECT)
> +    return (SUPPORT_COLOR | SUPPORT_BRIGHTNESS | SUPPORT_EFFECT)
> ```

Hi, i have the same issue. This fix should work but I don't know where I have to put to make it work.Can you help me? Thank you

**Comment by Snille** [comment]
@fraanz97 Here it is in "pictures". :)
Edit the file: custom_components/sp108e_ws2815.light/pyledshop/WifiLedShopLight.py b/pyledshop/WifiLedShopLight.py
I'm using the "Studio Code Server" addon for this (but here are many ways you can edit a file).
Go down a bit (around line 11) and change like this: Green is I changed the line, red is I removed a remove line.
![image](https://user-images.githubusercontent.com/1011699/190993848-1c06d5c3-e259-4913-8640-544da40bbcf0.png)
Then continue down to around line 134 and change like this:
![image](https://user-images.githubusercontent.com/1011699/190994531-640c5d9c-8669-4667-886b-4df6973eb44a.png)
Lastly go down to the end of the file and change like this:
![image](https://user-images.githubusercontent.com/1011699/190994632-c5e2d12e-00ad-4196-a8cb-2a910e4e4f91.png)
All done. Just restart HA. :)

**Comment by fraanz97** [comment]
> @fraanz97 Here it is in "pictures". :) Edit the file: custom_components/sp108e_ws2815/pyledshop/WifiLedShopLight.py I'm using the "Studio Code Server" addon for this (but here are many ways you can edit a file). Go down a bit (around line 11) and change like this: Green is I changed the line, red is I removed a line. ![image](https://user-images.githubusercontent.com/1011699/190993848-1c06d5c3-e259-4913-8640-544da40bbcf0.png) Then continue down to around line 133 and change like this: ![image](https://user-images.githubusercontent.com/1011699/190995998-44e6dad7-7ff2-4be1-8671-c1b892d77872.png) Lastly go down to the end of the file and change like this: ![image](https://user-images.githubusercontent.com/1011699/190994632-c5e2d12e-00ad-4196-a8cb-2a910e4e4f91.png) All done. Just restart HA. :)

Thank you so much. It works

**Comment by samhstein** [comment]
hi,

sorry for the delay been / still am traveling for a bit. if somebody can submit a pull request i can 
merge it, other wise will be close till the end of the month until i can make the changes and
test...


thanks, sam

**Comment by cskiwi** [comment]
@samhstein: Done: https://github.com/samhstein/sp108e_ws2815/pull/21

**Comment by samhstein** [comment]
updated both branches, will hopefully get the config-flow set as the default
