### ISSUE TITLE
HA 2020.12.1 not sending changes

### ISSUE THREAD

**Issue by mitsumaui** [samhstein/sp108e_ws2815#4]
Hey Sam!

I'm having an issue where HA 2012.12.1 is not sending any updates / changes to the SP108e, however can see incoming state changes when being togged via the "LED shop" app. What version did you have this working on? 

I've tried turning up debug logging but not seeing anything for the component.

- When using the "Light" Lovelace component, when changing the effect, colour, or brightness they change in the UI, but not on the LEDs. When I close / re-open the extended info, it reverts back to the state the controller is physically set to. I.e. change to rainbow, but close and re-open and it reverts back to solid / green which is set on the controller. 
- Power toggling is instantaneous and always up to date
- When using Developer states - I can set brightness or colour, however it does not take effect until you toggle power off/on again. 

I've plenty of other lights which work just fine - seems to be just this custom component I'm having issues with. Appreciate any thoughts or things to check! 

As a side, I did also try an older revision before the 'white support' was added but did not seem to make a difference.

**Comment by samhstein** [comment]
hi,

i am running, 2020.12.1, with the version before any merges. going to update to 2020.12.2, pull the latest and give that a try.
will let you know if it works for me.

thanks, sam

**Comment by samhstein** [comment]
pushed a fix, moved the merged code that returns when off down so commands would get sent when its on...

**Comment by mitsumaui** [comment]
Sorry for the delay! Thanks for making the adjustment! I've tested it and working much better now. Looks like I have different effect names to your repo so might go through those to adjust at some point! 

Will have a look to see if it can work with multiple controllers, and if there's a way to make this work with "PlatformNotReady" so it avoids errors if the controller is not online at HASS startup. 

Happy for this to be closed out! Good work on getting this put together, would be awesome to see this as a proper integration at some point!

**Comment by samhstein** [comment]
m,

don' really remember where the effects were grabbed from, but there are all in effects.py. the colors and names
on some don't make sense but was cool at xmas to have one with meteor red and one green ;-)

not sure how hard it is to take the code and do the registration auto configure magic....

multi controller should not be a problem have 2 now and will prolly end up with about 5, but been too busy
to get the last few installed, i just have two config lines:

# led strip
light:
  - platform: sp108e_ws2815
    host: 10.0.1.124
    name: 'family led'
    
  - platform: sp108e_ws2815
    host: 10.0.1.123
    name: 'living led'
